(() => {
  const DEMO={assessment:{assessment_id:"demo-dravyaguna-3",title:"Dravyaguna · Chapter 3 Assessment",curriculum_refs:["subject:dravyaguna"],questions:[
    {question_id:"q1",prompt:"Which principle is most useful for organising related dravyas during study?",points:1,options:[{option_id:"a",text:"Memorising each dravya as an isolated fact"},{option_id:"b",text:"Connecting source, properties, action and use"},{option_id:"c",text:"Studying only the common names"},{option_id:"d",text:"Grouping topics only by page number"}]},
    {question_id:"q2",prompt:"Which relationship best supports therapeutic application?",points:1,options:[{option_id:"a",text:"Properties → action → use"},{option_id:"b",text:"Page → chapter → book"},{option_id:"c",text:"Name → spelling → page"},{option_id:"d",text:"Source → index → appendix"}]}
  ]}};
  const key="aaptakosha.assessment.session", base=(window.AAPTAKOSHA_API_BASE||"").replace(/\/$/,""), learner=window.AAPTAKOSHA_LEARNER_ID||"demo-learner";
  async function request(path,options={}){if(!base)return null;const r=await fetch(base+path,{headers:{"Content-Type":"application/json"},...options}),b=await r.json();if(!r.ok)throw Error(b?.error?.message||"Assessment request failed");return b}
  function save(x){localStorage.setItem(key,JSON.stringify(x))} function load(){try{return JSON.parse(localStorage.getItem(key)||"null")}catch{return null}}
  async function start(id){const live=await request("/assessments/"+encodeURIComponent(id)+"/attempts",{method:"POST",body:JSON.stringify({learner_id:learner})});if(live?.data)return live.data;const x={attempt_id:"demo-"+Date.now(),assessment_id:DEMO.assessment.assessment_id,learner_id:learner,status:"in_progress",answers:[]};save(x);return{attempt:x,assessment:DEMO.assessment}}
  async function saveAnswers(session,answers){const live=await request("/attempts/"+encodeURIComponent(session.attempt_id)+"/answers",{method:"PUT",body:JSON.stringify({learner_id:learner,answers})});if(live?.data){save(live.data);return live.data}const x={...session,answers};save(x);return x}
  async function submit(session){const live=await request("/attempts/"+encodeURIComponent(session.attempt_id)+"/submit",{method:"POST",body:JSON.stringify({learner_id:learner})});if(live?.data){localStorage.setItem(key+".result",JSON.stringify(live.data));localStorage.removeItem(key);return live.data}const map=Object.fromEntries(session.answers||[]),a=DEMO.assessment,bd=a.questions.map(q=>{const s=map[q.question_id]||[],c=q.question_id==="q1"?["b"]:["a"],ok=s.length===c.length&&s.every(x=>c.includes(x));return{question_id:q.question_id,selected_option_ids:s,correct_option_ids:c,is_correct:ok,points:ok?q.points:0,maximum_points:q.points}}),score=bd.reduce((n,x)=>n+x.points,0),max=a.questions.reduce((n,x)=>n+x.points,0),result={attempt:{...session,status:"submitted"},assessment:{assessment_id:a.assessment_id,title:a.title},score,maximum_score:max,percent:Math.round(score*100/max),breakdown:bd,analytics:{attempt_count:1,submitted_attempt_count:1,best_score:score,best_percent:Math.round(score*100/max),latest_score:score}};localStorage.setItem(key+".result",JSON.stringify(result));localStorage.removeItem(key);return result}
  window.AaptaKoshaAssessment={start,saveAnswers,submit,load,DEMO,learner};
})();