(() => {
  const DEMO={assessment:{assessment_id:"demo-dravyaguna-3",title:"Dravyaguna · Chapter 3 Assessment",curriculum_refs:["subject:dravyaguna"],questions:[{question_id:"q1",prompt:"Which principle is most useful for organising related dravyas during study?",points:1,options:[{option_id:"a",text:"Memorising each dravya as an isolated fact"},{option_id:"b",text:"Connecting source, properties, action and use"},{option_id:"c",text:"Studying only the common names"},{option_id:"d",text:"Grouping topics only by page number"}]},{question_id:"q2",prompt:"Which relationship best supports therapeutic application?",points:1,options:[{option_id:"a",text:"Properties → action → use"},{option_id:"b",text:"Page → chapter → book"},{option_id:"c",text:"Name → spelling → page"},{option_id:"d",text:"Source → index → appendix"}]}]}};
  const key="aaptakosha.assessment.session",base=(window.AAPTAKOSHA_API_BASE||"/api").replace(/\/$/,""),learner=window.AAPTAKOSHA_LEARNER_ID||"demo-learner";
  async function request(path,options={}){try{const r=await fetch(base+path,{headers:{"Content-Type":"application/json"},...options}),b=await r.json();if(!r.ok)throw Error(b?.error?.message||"Assessment request failed");return b}catch(e){if(window.AAPTAKOSHA_API_BASE)throw e;return null}}
  function save(x){localStorage.setItem(key,JSON.stringify(x))}function load(){try{return JSON.parse(localStorage.getItem(key)||"null")}catch{return null}}
  async function start(id){const live=await request("/assessments/"+encodeURIComponent(id)+"/attempts",{method:"POST",body:JSON.stringify({learner_id:learner})});if(live?.data){save(live.data);return live.data}const a=DEMO.assessment,x={attempt_id:"demo-"+Date.now(),assessment_id:a.assessment_id,learner_id:learner,status:"in_progress",answers:[]},s={attempt:x,assessment:a};save(s);return s}
  async function saveAnswers(s,answers){const live=await request("/attempts/"+encodeURIComponent(s.attempt.attempt_id)+"/answers",{method:"PUT",body:JSON.stringify({learner_id:learner,answers})});const x=live?.data?{...s,attempt:live.data}:{...s,attempt:{...s.attempt,answers}};save(x);return x}
  async function submit(s){const live=await request("/attempts/"+encodeURIComponent(s.attempt.attempt_id)+"/submit",{method:"POST",body:JSON.stringify({learner_id:learner})});if(live?.data){localStorage.setItem(key+".result",JSON.stringify(live.data));localStorage.removeItem(key);return live.data}const map=Object.fromEntries(s.attempt.answers||[]),a=s.assessment,bd=a.questions.map(q=>{const x=map[q.question_id]||[],c=q.question_id==="q1"?["b"]:["a"],ok=x.length===c.length&&x.every(v=>c.includes(v));return{question_id:q.question_id,selected_option_ids:x,correct_option_ids:c,is_correct:ok,points:ok?q.points:0,maximum_points:q.points}}),score=bd.reduce((n,x)=>n+x.points,0),max=a.questions.reduce((n,x)=>n+x.points,0),r={attempt:{...s.attempt,status:"submitted"},assessment:{assessment_id:a.assessment_id,title:a.title},score,maximum_score:max,percent:Math.round(score*100/max),breakdown:bd,analytics:{attempt_count:1,submitted_attempt_count:1,best_score:score,best_percent:Math.round(score*100/max),latest_score:score}};localStorage.setItem(key+".result",JSON.stringify(r));localStorage.removeItem(key);return r}
  async function result(id){const live=await request("/attempts/"+encodeURIComponent(id)+"?learner_id="+encodeURIComponent(learner));return live?.data||null}
  window.AaptaKoshaAssessment={start,saveAnswers,submit,result,load,DEMO,learner};
})();