const state={chapter:null,items:[],filter:"all",query:"",progress:new Map(),revisionRefs:new Set(),selectedUnit:null,syncReady:false};
const grid=document.querySelector("#verseGrid"),search=document.querySelector("#verseSearch"),count=document.querySelector("#resultCount"),unitList=document.querySelector("#unitList"),chapterProgress=document.querySelector("#chapterProgress"),chapterProgressLabel=document.querySelector("#chapterProgressLabel"),recitationProgress=document.querySelector("#recitationProgress"),resumeButton=document.querySelector("#resumeButton"),syncState=document.querySelector("#syncState");
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const itemId=v=>v.verse_id||v.passage_id||"";const itemLabel=v=>v.verse_no??v.passage_no??itemId(v);const unitKey=(u,i)=>u.unit_id||("unit-"+String(i+1).padStart(2,"0"));const pkey=(t,id)=>t+":"+id;
async function api(path,options={}){const r=await fetch(path,{credentials:"same-origin",headers:{"Content-Type":"application/json",...(options.headers||{})},...options}),d=await r.json().catch(()=>({}));if(!r.ok){const e=Error(d?.error?.message||d?.error?.code||("HTTP "+r.status));e.status=r.status;throw e}return d}
function pf(t,id){return state.progress.get(pkey(t,id))||{status:"not_started",completion_percent:0}}
function parseRange(v){const m=String(v??"").match(/(\d+)\s*[-–]\s*(\d+)/);return m?{start:Number(m[1]),end:Number(m[2])}:null}
function unitItems(u){const refs=u.passage_refs||u.verse_refs;if(Array.isArray(refs)&&refs.length)return state.items.filter(x=>refs.includes(itemId(x)));const range=u.start_verse&&u.end_verse?{start:u.start_verse,end:u.end_verse}:parseRange(u.verses);if(range)return state.items.filter(x=>Number(x.verse_no)>=range.start&&Number(x.verse_no)<=range.end);return []}
function legacyTextToItems(text){const matches=[...String(text??"").matchAll(/(॥|।)\s*(\d+)\s*(?:॥|।)/g)];if(!matches.length)return[{verse_no:1,verse_id:"legacy-01",sanskrit_original:String(text??"")}];let out=[],last=0;for(const m of matches){const end=m.index+m[0].length,chunk=String(text??"").slice(last,end).trim();if(chunk)out.push({verse_no:Number(m[2]),verse_id:"legacy-"+String(m[2]).padStart(2,"0"),sanskrit_original:chunk});last=end}return out}
function legacyRangeText(value,verse){const entries=Array.isArray(value)?value:(value&&typeof value==="object"?Object.values(value):[]);const hit=entries.find(x=>{const r=parseRange(x.range||x.verses||x.start_verse+"-"+x.end_verse);return r&&verse>=r.start&&verse<=r.end});return hit?.text||""}
function unitComplete(i){const u=state.chapter.learning_units[i];return pf("samhita_unit",state.chapter.chapter_id+"."+unitKey(u,i)).completion_percent===100}
function reciteItems(){return state.items.filter(v=>v.recitation_status==="ncism_explicit")}
function chapterPct(){const n=state.chapter.learning_units.length,d=state.chapter.learning_units.filter((_,i)=>unitComplete(i)).length;return n?Math.round(d/n*100):0}
function recitePct(){const a=reciteItems(),d=a.filter(v=>pf("samhita_recitation",state.chapter.chapter_id+"."+itemId(v)).completion_percent===100).length;return a.length?Math.round(d/a.length*100):0}
async function loadProgress(){try{const d=await api("/api/progress");state.progress.clear();(d.progress||[]).forEach(x=>state.progress.set(pkey(x.resource_type,x.resource_id),x));state.syncReady=true;syncState.textContent="✓ प्रगति sync हो रही है"}catch(e){state.syncReady=false;syncState.textContent=e.status===401?"प्रगति sync के लिए sign in करें":"प्रगति sync अभी उपलब्ध नहीं"}try{const d=await api("/api/revision?content_id="+encodeURIComponent(state.chapter.chapter_id));state.revisionRefs=new Set((d.data?.recommendations||[]).map(x=>x.content_ref))}catch{state.revisionRefs=new Set()}}
async function saveProgress(type,id,pct){if(!state.syncReady)return false;try{const d=await api("/api/progress",{method:"POST",body:JSON.stringify({resource_type:type,resource_id:id,status:pct>=100?"completed":pct>0?"in_progress":"not_started",completion_percent:pct})});state.progress.set(pkey(type,id),d.progress);return true}catch{return false}}
async function toggleUnit(i){const u=state.chapter.learning_units[i],id=state.chapter.chapter_id+"."+unitKey(u,i);if(await saveProgress("samhita_unit",id,unitComplete(i)?0:100)){await saveProgress("samhita_chapter",state.chapter.chapter_id,chapterPct());renderAll()}}
async function toggleRecitation(v){const id=state.chapter.chapter_id+"."+itemId(v),pct=pf("samhita_recitation",id).completion_percent;if(await saveProgress("samhita_recitation",id,pct===100?0:100))renderAll()}
function unitMatches(v,i){return unitItems(state.chapter.learning_units[i]).some(x=>itemId(x)===itemId(v))}
function matches(v){const q=state.query.trim().toLowerCase(),i=state.chapter.learning_units.findIndex((_,n)=>unitMatches(v,n));if(state.selectedUnit!==null&&i!==state.selectedUnit)return false;const t=[itemLabel(v),v.section,v.type,v.sanskrit_original,v.translation_hi,v.explanation_hi,v.tika_sarvangasundara_hi,v.tika_ayurvedarasayana_hi].join(" ").toLowerCase();if(q&&!t.includes(q))return false;if(state.filter==="recitation")return v.recitation_status==="ncism_explicit";if(state.filter==="revision")return state.revisionRefs.has(itemId(v))||(i>=0&&unitComplete(i));return true}
function renderUnits(){unitList.innerHTML=state.chapter.learning_units.map((u,i)=>{const members=unitItems(u),first=members[0],last=members[members.length-1],range=u.start_verse&&u.end_verse?u.start_verse+"–"+u.end_verse:first&&last?itemLabel(first)+"–"+itemLabel(last):"";return '<button class="unit-card '+(state.selectedUnit===i?"active":"")+'" data-unit="'+i+'"><span class="unit-number">'+String(i+1).padStart(2,"0")+'</span><span class="unit-copy"><strong>'+esc(u.title_hi||("Unit "+(i+1)))+'</strong><small>'+esc(range?"अंश "+range:"")+'</small></span><span class="unit-state">'+(unitComplete(i)?"✓ पूर्ण":"○ बाकी")+'</span></button>'}).join("")}
function renderStudyAids(){const aids=Array.isArray(state.chapter.study_aids)?state.chapter.study_aids:[];return aids.length?'<section class="study-aids"><div class="section-label">अध्ययन-सहायक</div>'+aids.map(a=>{if(a.type==="flow_diagram")return '<details class="panel" open><summary>'+esc(a.title_hi||"अध्ययन-प्रवाह")+'</summary><div class="study-flow">'+(a.steps||[]).map((s,i)=>'<span class="flow-step"><b>'+String(i+1)+'</b> '+esc(s)+'</span>').join('<span class="flow-arrow">→</span>')+'</div></details>';const cols=a.columns||[],rows=a.rows||[];return '<details class="panel"><summary>'+esc(a.title_hi||"तुलनात्मक सारणी")+'</summary><div class="study-table-wrap"><table class="study-table"><thead><tr>'+cols.map(x=>'<th>'+esc(x)+'</th>').join("")+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(x=>'<td>'+esc(x)+'</td>').join("")+'</tr>').join("")+'</tbody></table></div>'+(a.note_hi?'<p><strong>नोट:</strong> '+esc(a.note_hi)+'</p>':"")+'</details>'}).join("")+'</section>':""}\nfunction render(){renderUnits();const a=state.items.filter(matches),noun=Array.isArray(state.chapter.passages)?"अंश":"श्लोक";count.textContent=a.length+" / "+state.items.length+" "+noun;grid.innerHTML=renderStudyAids()+a.map(v=>{const r=v.recitation_status==="ncism_explicit",done=pf("samhita_recitation",state.chapter.chapter_id+"."+itemId(v)).completion_percent===100;return '<article id="item-'+esc(itemId(v))+'" class="verse-card '+(r?"recite":"")+'"><div class="verse-head"><span class="verse-number">'+(Array.isArray(state.chapter.passages)?"अंश ":"श्लोक ")+esc(itemLabel(v))+'</span>'+(r?'<span class="recite-badge">NCISM Recitation</span>':"")+(r?'<button class="recite-button '+(done?"done":"")+'" data-recite="'+esc(itemId(v))+'">'+(done?"✓ मुखस्थ":"○ मुखस्थ")+'</button>':"")+'<button class="audio" data-audio="'+esc(v.sanskrit_original)+'"'+(v.audio?.url?' data-audio-src="'+esc(v.audio.url)+'"':'')+'>'+((v.audio?.url&&v.audio.type==="recording")?"🎧 Audio":"🔊 Read")+'</button></div><div class="section-label">'+esc(v.section||v.type||"")+'</div><div class="sanskrit">'+esc(v.sanskrit_original).replace(/\n/g,"<br>")+'</div><div class="panel"><strong>हिन्दी अर्थ</strong><p>'+esc(v.translation_hi)+'</p></div><div class="panel"><strong>व्याख्या</strong><p>'+esc(v.explanation_hi)+'</p></div><details><summary>सर्वाङ्गसुन्दरी — टीका अनुवाद</summary><p>'+esc(v.tika_sarvangasundara_hi||v.tika_hi)+'</p></details><details><summary>आयुर्वेदरसायन — टीका अनुवाद</summary><p>'+esc(v.tika_ayurvedarasayana_hi||"उपलब्ध नहीं")+'</p></details></article>'}).join("")||'<div class="empty">इस mode/search के लिए कोई श्लोक या अंश नहीं मिला।</div>'}
function renderMetrics(){const cp=chapterPct(),rp=recitePct();chapterProgress.style.width=cp+"%";chapterProgressLabel.textContent=cp+"% chapter complete";recitationProgress.style.width=rp+"%";const a=reciteItems(),d=a.filter(v=>pf("samhita_recitation",state.chapter.chapter_id+"."+itemId(v)).completion_percent===100).length;document.querySelector("#recitationLabel").textContent=a.length?rp+"% · "+d+"/"+a.length+" श्लोक":"इस अध्याय के लिए अलग NCISM recitation list निर्दिष्ट नहीं";document.querySelector(".study-toolbar button[data-filter=recitation]").hidden=!a.length;document.querySelector("#recitationMeta").textContent=a.length?"NCISM recitation marked":"NCISM scope · recitation list not separately specified";const n=state.chapter.learning_units.findIndex((_,i)=>!unitComplete(i));resumeButton.textContent=n===-1?"✓ अध्याय पूर्ण":"▶ "+(n===0?"शुरू करें":"जारी रखें")+" · Unit "+(n+1);resumeButton.disabled=n===-1}
function renderAll(){renderMetrics();render()}
function speak(t,src){if(src){const a=new Audio(src);a.play().catch(()=>speakTts(t));return}speakTts(t)}
function speakTts(t){if(!("speechSynthesis"in window)){alert("इस ब्राउज़र में Read/Audio उपलब्ध नहीं है।");return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang="hi-IN";speechSynthesis.speak(u)}
function assessmentIdForChapter(id){const m=/^charaka\.sutra\.(\d{2})$/.exec(id||"");if(m)return m[1]==="01"?"charaka.sutra.01.ncism-revision":id+".revision";const a=/^ashtanga\.hridaya\.sutra\.(\d{2})$/.exec(id||"");return a?id+".revision":null}
async function init(){const params=new URLSearchParams(location.search),id=params.get("chapter")||"charaka.sutra.01",mode=params.get("mode"),focus=params.get("verse")||"",d=await api("/api/content/samhita?content_id="+encodeURIComponent(id));state.chapter=d.data;state.items=(Array.isArray(state.chapter.verses)?state.chapter.verses:Array.isArray(state.chapter.passages)?state.chapter.passages:legacyTextToItems(state.chapter.sanskrit_text||"")).map((v,i)=>{const n=Number(v.verse_no??v.passage_no??i+1);return {...v,verse_no:n,verse_id:v.verse_id||"legacy-"+String(n).padStart(2,"0"),sanskrit_original:v.sanskrit_original||v.text||"",translation_hi:v.translation_hi||legacyRangeText(state.chapter.hindi_translation,n),explanation_hi:v.explanation_hi||"",tika_hi:v.tika_hi||legacyRangeText(state.chapter.commentary_mapping,n),_index:i}});document.querySelector("#chapterTitle").textContent=state.chapter.title_hi||state.chapter.title;const noun=Array.isArray(state.chapter.passages)?"अंश":"श्लोक";document.querySelector("#verseCount").textContent=state.chapter.verse_count+" "+noun;document.querySelector(".unit-section .eyebrow").textContent=state.chapter.learning_units.length+" learning units";const actions=document.querySelector("#chapterActions"),aid=assessmentIdForChapter(id);if(actions&&aid)actions.innerHTML='<a class="chapter-test" href="./assessment.html?assessment_id='+encodeURIComponent(aid)+'&chapter='+encodeURIComponent(id)+'">✦ Chapter Revision Test</a><a class="chapter-revision" href="?chapter='+encodeURIComponent(id)+'&mode=revision">↻ Weak Content Revision</a>';if(mode==="revision")state.filter="revision";await loadProgress();renderAll();if(focus){const target=state.items.find(x=>String(x.verse_no??"")===focus||String(x.passage_no??"")===focus||itemId(x)===focus);if(target){const el=document.querySelector("#item-"+CSS.escape(itemId(target)));if(el){el.classList.add("focus-verse");el.scrollIntoView({behavior:"smooth",block:"center"});setTimeout(()=>el.classList.remove("focus-verse"),2200)}}}}
document.querySelector(".study-toolbar").addEventListener("click",e=>{const b=e.target.closest("button[data-filter]");if(!b)return;document.querySelectorAll(".study-toolbar button[data-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.filter=b.dataset.filter;state.selectedUnit=null;render()});
unitList.addEventListener("click",e=>{const b=e.target.closest("[data-unit]");if(!b)return;state.selectedUnit=Number(b.dataset.unit);state.filter="all";document.querySelectorAll(".study-toolbar button[data-filter]").forEach(x=>x.classList.remove("active"));document.querySelector('.study-toolbar button[data-filter="all"]')?.classList.add("active");render()});
grid.addEventListener("click",async e=>{const a=e.target.closest("[data-audio]");if(a)speak(a.dataset.audio,a.dataset.audioSrc);const b=e.target.closest("[data-recite]");if(b){const v=state.items.find(x=>itemId(x)===b.dataset.recite);if(v)await toggleRecitation(v)}});
resumeButton.addEventListener("click",()=>{const n=state.chapter.learning_units.findIndex((_,i)=>!unitComplete(i));if(n>=0){state.selectedUnit=n;render();document.querySelector('[data-unit="'+n+'"]')?.scrollIntoView({behavior:"smooth",block:"center"})}});
document.querySelector("#markUnitComplete").addEventListener("click",()=>{if(state.selectedUnit!==null)toggleUnit(state.selectedUnit)});
search.addEventListener("input",e=>{state.query=e.target.value;render()});
init().catch(e=>{grid.innerHTML='<div class="empty">अध्याय अभी लोड नहीं हो सका।</div>';syncState.textContent=e?.message||"अध्याय लोड नहीं हुआ"});
