-- NCISM-verified AyUG-ST Paper I and Paper II topic hierarchy.
DELETE FROM curriculum_nodes
WHERE curriculum_id='bams_ncism_3' AND subject_id='AyUG-ST'
  AND node_type='topic';

INSERT OR IGNORE INTO curriculum_nodes
(node_id,curriculum_id,curriculum_version,subject_id,parent_node_id,node_type,code,name,source_reference,source_locator,marks,sort_order)
VALUES
('y3-st-1','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','1','Introduction to Shalya Tantra (Introduction to development of surgery)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',15,10),
('y3-st-2','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','2','Yantra and Shastra (Blunt and sharp instruments)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',NULL,20),
('y3-st-3','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','3','Nirjantukarana (Sterilization)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',NULL,30),
('y3-st-4','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','4','Sangyaharana (Anaesthesia)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',NULL,40),
('y3-st-5','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','5','Trividha Karma (Pre, Operative and Post Operative care)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',NULL,50),
('y3-st-6','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','6','Shastra Karma (Operative procedure)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',NULL,60),
('y3-st-7','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','7','Yogya (Experimental Surgical Training)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',NULL,70),
('y3-st-8','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','8','Marma (Vital points)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',5,80),
('y3-st-9','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','9','Kshara Karma','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',15,90),
('y3-st-10','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','10','Agnikarma','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',NULL,100),
('y3-st-11','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','11','Raktamokshana','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',NULL,110),
('y3-st-12','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','12','Bandha Vidhi','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',6,120),
('y3-st-13','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','13','Pranashta Shalya','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',NULL,130),
('y3-st-14','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','14','Fluid, Electrolyte, Acid Base Balance and Nutrition in surgical practice','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',5,140),
('y3-st-15','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','15','Rakta','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',NULL,150),
('y3-st-16','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','16','Life Saving and Emergency Medicines in surgical practice (Prana Rakshaka and Atyayika Dravya)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',4,160),
('y3-st-17','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','17','Naidanik Vidhi (Diagnostic techniques)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',NULL,170),
('y3-st-18','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','18','Shat Kriyakala in surgical practice','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',5,180),
('y3-st-19','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','19','Samanya Vyadhi Parichaya','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',10,190),
('y3-st-20','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','20','Vrana','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',10,200),
('y3-st-21','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','21','Kshudra Roga','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',3,210),
('y3-st-22','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','22','Manya Vikara','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',5,220),
('y3-st-23','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','23','Sira Vikara (Venous Disorders)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',10,230),
('y3-st-24','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','24','Dhamani Vikara (Arterial disorders)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',NULL,240),
('y3-st-25','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','25','Snayu Vikara (Diseases of tendons and ligaments)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',5,250),
('y3-st-26','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper1','topic','26','AIDS - HIV and Hepatitis (B and C)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 1',2,260),
('y3-st-27','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','27','Bhagna (Skeletal Injuries)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',10,270),
('y3-st-28','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','28','Asthi Sandhi Vikara (Diseases of Bone and Joints)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',5,280),
('y3-st-29','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','29','Shirobhighata (Cranio-cerebral Injurie/ Disorders)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',6,290),
('y3-st-30','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','30','Kasheruka Vikara (Diseases of Spine)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',6,300),
('y3-st-31','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','31','Stana Roga (Diseases of Breast)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',5,310),
('y3-st-32','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','32','Urah Vikara (Diseases of Chest)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',3,320),
('y3-st-33','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','33','Anna Nalika Vikara (Diseases of Oesophagus)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',2,330),
('y3-st-34','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','34','Gulma Roga','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',2,340),
('y3-st-35','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','35','Shoola Vyadhi','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',2,350),
('y3-st-36','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','36','Udara Roga','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',5,360),
('y3-st-37','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','37','Aamashaya Evam Adho-Aamashaya Vikara (Diseases of Stomach and Duodenum)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',12,370),
('y3-st-38','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','38','Kshudrantra Vikara (Diseases of Small Intestine)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',12,380),
('y3-st-39','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','39','Brihadantra Vikara (Diseases of Large Intestine)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',12,390),
('y3-st-40','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','40','Guda Vikara (Diseases of Rectum and Anal Canal)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',12,400),
('y3-st-41','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','41','Udarabhighata (Abdominal Injuries)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',12,410),
('y3-st-42','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','42','Yakrit Vikara (Diseases of Liver)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',15,420),
('y3-st-43','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','43','Pittashaya Vikara (Diseases of Gall Bladder)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',15,430),
('y3-st-44','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','44','Agnyashaya Vikara (Diseases of Pancreas)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',5,440),
('y3-st-45','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','45','Pleeha Vikara (Diseases of Spleen)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',5,450),
('y3-st-46','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','46','Vrikka Evam Mutravahini Vikara (Diseases of Kidney and Ureters)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',15,460),
('y3-st-47','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','47','Mutrashaya Vikara (Diseases of Urinary bladder)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',15,470),
('y3-st-48','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','48','Mutraghata and Mutrakrichra','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',15,480),
('y3-st-49','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','49','Paurusha Granthi Vikara (Diseases of Prostate)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',15,490),
('y3-st-50','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','50','Mutramarga Vikara (Diseases of Urethra)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',15,500),
('y3-st-51','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','51','Medhra Vikara (Diseases of Penis)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',15,510),
('y3-st-52','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','52','Mushka Evum Vrishan Vikara (Diseases of Scrotum and Testis)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',15,520),
('y3-st-53','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','53','Vriddhi Roga','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',15,530),
('y3-st-54','bams_ncism_3','2021-22','AyUG-ST','y3-st-paper2','topic','54','Antravriddhi (Hernia)','NCISM AyUG-ST','Table 6F: Distribution of theory examination, Paper 2',15,540);
